# Site settings
title: Grace Documentation
email: pcowal@gmail.com
description: "Step By Step Introduction to Grace"
baseurl: ""
url: "http://gracelang.org"
github_username:  petercowal

# Build settings
markdown: kramdown
permalink: pretty
