#This makefile provides standard build and serve functionality
#through jekyll for this project

all:
	$(info Building the website... Running command:)
	jekyll build relative
	@echo "*****************************************************************"
	@echo "The website has been built and is stored in _site folder. It can now be"
	@echo "added to a server. If you wish to run it on localhost, use \"make serve\""

serve:
	@echo "Running command:"
	jekyll serve


build:
	$(info Building the website... Running command:)
	jekyll build relative
	@echo "*****************************************************************"
	@echo The website has been built and is stored in _site folder. It can now be
	@echo added to a server. If you wish to run it on localhost, use "make serve"
